export default {
  '问卷名称': 'Questionnaire name',
  '添加问卷': 'Add a questionnaire',
  '试题管理': 'Question management',
  '请输入题目名称': 'Please enter question name',
  '开头语': 'Opening words',
  '结束语': 'Ending words',
  '标题': 'Title',
  '从题库添加': 'Add from question bank',
  '收藏到题库': 'Collect to question bank',
  '跳转选择': 'Jump selection',
  '请输入题目id': 'Please enter the question ID',
  '题目数量': 'Number of questions',
  '跳转规则': 'Jump rules',
  '修改成功': 'Modification successful',
  '添加成功': 'Added successfully',
  '跳转至': 'Jump to',
  '收藏成功': 'Collection successful',
  '题库中已存在': 'Already exists in question bank ',
  '从题库中选择': 'Select from question bank',
  '“我是试题标题一”、“我是试题标题二”因为排序调整，导致跳转逻辑冲突，跳转逻辑系统已自动删除，请检查。': 'Due to order adjustment, the question jumping logic of \'question 1' & 'question 2\' has encountered a conflict, and the jump logic system has been automatically deleted, please check.',
  '客户姓名': 'Customer Name',
  '性别': 'Gender',
  '客户电话1': 'Customer phone 1',
  '客户电话2': 'Customer phone 2',
  '客户类型': 'Customer type',
  '客户级别': 'Customer level',
  '关联客户编号': 'Associated customer number',
  '问卷任务编号': 'Questionnaire task number',
  '界面仅为问卷预览界面，问卷回访界面会增加业务信息。': 'The interface is only a questionnaire preview page, and business information will be added in the official questionnaire filling interface.',
  '问卷信息': 'Questionnaire information',
  '请选择选项': 'Please select an option',
  '这是问卷预览界面，不允许提交': 'This is the questionnaire preview page, submission is not allowed',
  '明细': 'Details',
  '分配': 'Assign',
  '选择问卷': 'Select questionnaire',
  '请选择问卷': 'Please select a questionnaire',
  '任务备注': 'Task notes',
  '这是第一个问卷啊': 'This is the first questionnaire',
  '问卷总数': 'Total number of questionnaires',
  '已分配数': 'Assigned',
  '待分配数': 'To be assigned',
  '已分配率': 'Assigned rate',
  '已完成数': 'Completed',
  '未完成数': 'Unfinished',
  '已完成率': 'Completed rate',
  '任务创建时间': 'Task creation time',
  '查看明细': 'View details',
  '任务分配': 'Task assignment',
  '问卷状态': 'Questionnaire status',
  '任务名称': 'Task name',
  '导入数据': 'Import data',
  '批量分配': 'Bulk assigning',
  '分配(转移)': 'Assign (transfer)',
  '未分配': 'unassigned',
  '已分配未回访': 'Assigned but not returned',
  '已回访': 'Returned',
  '回访人': 'Return visitor',
  '回访时间': 'Return visit time',
  '分配人': 'Assignee',
  '分配时间': 'Assigning time',
  '客户名称': 'Customer name',
  '转移': 'Rransfer',
  '已选中的用户': 'Selected user',
  '请输入标题': 'Please enter a title',
  '插入填空项': 'Insert fill-in-the-blank item',
  '展现形式': 'Display form',
  '无条件跳转至': 'Unconditional jump to',
  '按问卷试题顺序往下': 'Scroll down in order of questions',
  '多行文本框行高': 'row height of multiline text box '
}
