export default {
  '分组管理': 'Group management',
  '添加下级分组': 'Add subgroups',
  '显示子级分组人员：': 'Show subgroup members:',
  '分组名称': 'Group name',
  '上级分组': 'Superior group',
  '作为一级分组': 'Set as first-level group',
  '请输入分组名称': 'Please enter a group name',
  '请输入少于10个字符': 'Please enter less than 10 characters',
  '所属分组': 'Group',
  '请选择所属分组': 'Please select a group',
  '作者': 'Author',
  '使用账号': 'Apply username',
  '请输入作者名称': 'Please enter author name',
  '发送时间': 'Sending time',
  '立即发送': 'Send immediately',
  '定时发送': 'Scheduled sending',
  '请选择定时发送时间': 'Please select a scheduled sending time',
  '发送范围': 'Sending range',
  '请输入标题': 'Please enter a title',
  '标题长度不得超过20': 'Title length must not exceed 20',
  '内容': 'Content',
  '请输入内容': 'Please enter content',
  '保存为草稿': 'Save as draft',
  '成员阅读情况': 'Reading feedback',
  '已读·{0}': 'Read · {0}',
  '未读·{0}': 'Unread · {0}',
  '已发送': 'Sent',
  '发送中': 'sending',
  '草稿': 'Draft',
  '发送公告': 'Send an announcement',
  '修改时间': 'Change the time',
  '已读': 'Read',
  '未读': 'Unread',
  '选择定时发送的时间': 'select a scheduled sending time',
  '阅读情况': 'Reading feedback',
  '取消后将变为草稿，确定取消？': 'After cancellation, it will be saved as a draft. Are you sure you want to cancel it?',
  '确定删除这条公告吗？': 'Are you sure you want to delete this announcement?'
}
