export default {
  '语言': 'language',
  '搜索': 'search',
  '重置': 'reset',
  '用户名': 'user name',
  '请输入用户名': 'please enter user name',
  '真实姓名': 'actual name ',
  '请输入真实姓名': 'please enter actual name ',
  '所属角色': 'belonging role',
  '请选择': 'please choose',
  '所属部门': 'belonging department',
  '状态': 'status',
  '启用': 'enable',
  '禁用': 'disabled',
  '性别': 'gender',
  '男': 'male',
  '女': 'Female',
  '手机号码': 'cellphone number',
  '请输入手机号码': 'Please enter the phone number',
  '分机号码': 'Extension Number',
  '请输入分机号码': 'Please enter an extension number',
  '添加': 'Add to',
  '导入': 'import',
  '导出': 'export',
  '批量删除': 'batch deletion',
  '批量编辑': 'bulk editing',
  '操作': 'operate',
  '在线状态': 'online status',
  '在线': 'online',
  '离线': 'offline',
  '部门负责人': 'head of department ',
  '是': 'Yes',
  '否': 'no',
  '最后登录时间': 'last login time',
  '最后修改人': 'last modified by',
  '最后修改时间': 'Last Modified',
  '编辑': 'edit',
  '更多': 'More',
  '删除': 'delete',
  '一键登录': 'One-click login',
  '模板下载': 'Template download',
  '用户导入模板': 'User import template',
  '大小写字母': 'uppercase and lowercase letters',
  '特殊字符': 'Special characters',
  '字母': 'letter',
  '新消息通知': 'New message notification',
  '访问范围': 'access range',
  '设置': 'set up',
  '备注': 'Remark',
  '保存': 'save',
  '修改': 'Revise/modify',
  '关闭': 'closure',
  '密码': 'password',
  '请输入密码': 'Please enter password',
  '请选择角色': 'Please select a role',
  '请选择部门': 'Please select a department',
  '头像': 'Avatar/profile',
  '图片尺寸为 100 X 100': 'Image size is 100 X 100',
  '您确认要删除该记录吗？': 'Are you sure you want to delete this record?',
  '您确认要删除选中的记录吗？': 'Are you sure you want to delete the selected records?',
  '导入数据': 'Import Data',
  '导出数据': 'export data',
  '选择文件': 'Select the file',
  '我的任务': 'my task',
  '请输入导出文件名称': 'Please enter the export file name',
  '请输入文件名搜索': 'Please enter file name to search',
  '未开始': 'has not started',
  '总导出数: ': 'Total exports',
  '已导出数: ': 'Exported',
  '已完成': 'completed',
  '失败': 'fail',
  '查看': 'Check',
  '下载': 'download',
  '所有任务': 'all tasks',
  '请选择要导入的文件': 'Please select a file to import',
  '文件名': 'file name',
  '创建时间': 'creation time',
  '开始时间': 'Starting time',
  '耗时': 'time consuming',
  '任务状态': 'task status',
  '创建人': 'founder',
  '创建部门': 'Create a department',
  '导入文件': 'Importing files',
  '导出文件名称': 'export file name',
  '文件大小': 'File size',
  '文件【{0}】上传中...': 'File [{0}] is uploading...',
  '文件【{0}】上传完成': 'File [{0}] upload completed',
  '文件【{0}】上传失败': 'File [{0}] failed to upload',
  '上传的是非图片格式': 'Uploaded in non-image format',
  '注意': 'Notice',
  '排序': 'sort',
  '编号': 'serial number',
  '名称': 'name',
  '请输入部门名称': 'Please enter department name',
  '用户': 'user',
  '部门': 'Department',
  '角色': 'Role',
  '清空': 'empty/clear',
  '您确定要清空所有记录吗？': 'Are you sure you want to clear all records?',
  '类型': 'Types of',
  '角色名称': 'Role Name',
  '权限设置': 'Permission settings',
  '功能暂未开放': 'Feature not yet available',
  '请输入角色名称': 'Please enter a role name',
  '请输入角色名称搜索': 'Please enter character name to search',
  '显示第 {0} 条到 {1} 条记录, 一共 {2} 条': 'Showing records {0} to {1} out of {2}',
  '全部': 'all',
  '待处理': 'To be processed',
  '已处理': 'processed',
  '确认': 'confirm',
  '取消': 'Cancel',
  '回复': 'Reply',
  '提交': 'submit',
  '处理人': 'handler',
  '处理时间': 'processing time',
  '删除成功': 'successfully deleted',
  '修改成功': 'Successfully modified',
  '添加成功': 'Added successfully',
  '开': 'open',
  '关': 'close',
  '发送': 'send',
  '请输入内容': 'Please enter content',
  '发送人': 'sender',
  '发送成功': 'Sent successfully',
  '发送失败': 'Failed to send',
  '日期': 'date',
  '系统名称': 'system name',
  '请输入系统名称': 'Please enter a system name',
  '系统编号': 'system number',
  '请输入系统编号': 'Please enter system number',
  '主题': 'theme',
  '收件人': 'recipient',
  '发件人': 'sender',
  '收件时间': 'Pickup time',
  '发送时间': 'send time',
  '批量发送': 'Bulk send',
  '彻底删除': 'Remove completely',
  '详情': 'Details',
  '操作成功': 'Successful operation',
  '请选择邮箱地址': 'Please select an email address',
  '请输入邮箱地址': 'Please input the email address',
  '请输入Subject': 'Please enter Subject',
  '邮件模板': 'email template',
  '模板引用': 'template reference',
  '邮箱格式不正确': 'E-mail format is incorrect',
  '上传文件格式错误': 'The uploaded file is in the wrong format',
  '适用订单状态': 'Applicable order status',
  '模板名称': 'template name',
  '业务场景': 'Business scene',
  '可用模板': 'Available templates',
  '选择': 'choose',
  '模板ID': 'Template ID',
  '邮件模板标题': 'Email Template Header',
  '使用次数': 'usage count',
  '绑定工单号': 'Bind work order number',
  '回复全部': 'Reply all',
  '转发': 'Forward',
  '创建工单': 'Create a ticket',
  '工单号': 'Work order number',
  '请输入工单号': 'Please enter the work order number',
  '创建流程': 'Create a process',
  '未修改工单号': 'Unmodified work order number',
  '转发邮件': 'forward mail',
  '回复邮件': 'Reply Mail',
  '写邮件': 'write an email',
  '图标': 'icon',
  '是否启用': 'Whether to enable',
  '是否显示': 'whether to display',
  '视图': 'view',
  '复制': 'copy',
  '数据窗口': 'data window',
  '可访问': 'accessible',
  '权限': 'permission',
  '展开': 'expand',
  '收起': 'put away',
  '任务名称': 'mission name',
  '请输入任务名称': 'Please enter a task name',
  '任务类型': 'task type',
  '进行中': 'in progress',
  '已结束': 'over',
  '结束时间': 'End Time',
  '最小值': 'minimum value',
  '最大值': 'maximum value',
  '对': 'right',
  '错': 'wrong',
  '单选': 'single choice',
  '多选': 'Multiple choice',
  '暂无数据': 'No data',
  '请输入用户名称搜索': 'Please enter username to search',
  '请输入部门名称搜索': 'Please enter the department name to search',
  '确定': 'Sure',
  '返回': 'return',
  '办理方式': 'handling method',
  '包含': 'Include',
  '等于': 'equal',
  '不包含': 'does not contain',
  '不等于': 'not equal to',
  '大于': 'greater than ',
  '小于': 'less than',
  '大于等于': 'greater than or equal to',
  '小于等于': 'less than or equal to',
  '不开始于': 'does not start with',
  '不结束于': 'does not end with',
  '选择字段': 'select field',
  '只读': 'read only',
  '可见不可编可提交': 'Visible, not editable and submittable',
  '允许': 'allow',
  '可见可编可提交': 'Visible, editable and submittable',
  '必填': 'Required',
  '隐藏': 'hide',
  '不可见可提交': 'Invisible to submit',
  '不可见不可提交': 'Invisible and unsubmittable',
  '测试': 'test',
  '显示': 'show',
  '单行文本': 'single line text',
  '下拉框': 'drop down box',
  '关联数据': 'Linked Data',
  '日期时间': 'date time',
  '多行文本': 'multiline text',
  '单选框': 'Single box',
  '复选框': 'checkbox',
  '编辑器': 'editor',
  '图片': 'picture',
  '附件': 'Appendix',
  '级联选择': 'Cascade selection',
  '开关': 'switch',
  '评分': 'score',
  '组织结构': 'organizational structure',
  '子表': 'child table',
  '数字': 'number',
  '地址': 'address',
  '树选择': 'tree selection',
  '标签': 'Label',
  'UI组件': 'UI components',
  '刷新排序': 'refresh sort',
  '系统默认': 'system default',
  '自定义': 'customize',
  '工具栏菜单': 'Toolbar menu',
  '配置': 'configure',
  '授权': 'Authorize',
  '无': 'without',
  '唯一': 'only',
  '导航': 'navigation',
  '更新缓存': 'refresh cache',
  '添加数据表': 'add data table',
  '导出数据表概览': 'Export data table overview',
  '导出数据表字段': 'Export data table fields',
  '数据表同步': 'Data table synchronization',
  '高级搜索': 'Advanced Search',
  '输入关键字搜索': 'Enter a keyword to search',
  '数据表名称': 'data table name',
  '字段管理': 'Field management',
  '表单视图': 'form view',
  '显示名称': 'show name',
  '分类名称': 'Category Name',
  '请输入名称': 'Please enter a name',
  '请输入2-20个字符': 'Please enter 2-20 characters',
  '基础设置': 'Basic Settings',
  '百分比': 'percentage',
  '表单填写不符合要求，请参考页面内具体提示修改': 'The form filling does not meet the requirements, please refer to the specific prompts on the page to modify',
  '帮助说明': 'Help description',
  '链接地址': 'link address',
  '请输入链接地址': 'Please enter link address',
  '条件设置': 'Condition setting',
  '姓名': 'Name',
  '电话': 'telephone',
  '预览': 'preview',
  '评分题': 'graded questions',
  '单选题': 'single choice',
  '多选题': 'multiple choice',
  '判断题': 'True or False',
  '填空题': 'fill in the blank',
  '简答题': 'short answer questions',
  '文字描述': 'word description',
  '题型': 'Question type',
  '请选择题型': 'Please select a topic',
  '是否必填': 'Is it required',
  '单选按钮': 'single button',
  '组件': 'components',
  '选项1': 'Option 1',
  '选项2': 'Option 2',
  '请选择字段': 'Please select a field',
  '请输入': 'please enter',
  '未设置': 'not set',
  '清除': 'clear',
  '展现形式': 'Display form',
  '请选择视图': 'Please select a view',
  '如果': 'if',
  '当前用户': 'Current user',
  '当前用户所属部门': 'The current user\'s department',
  '当前用户所属角色': 'The role of the current user',
  '开始于': 'start with',
  '结束于': 'ends at',
  '不为空': 'not null',
  '属于': 'belong',
  '不属于': 'Does not belong',
  '那么': 'So',
  '公式编辑器': 'formula editor',
  '示闲': 'show off',
  '下班': 'get off work',
  '开会': 'meeting',
  '休息': 'rest',
  '示忙': 'busy',
  '登出': 'Sign out',
  '示忙总次数': 'total busy times',
  '示忙总时长': 'total busy time',
  '呼入': 'call in',
  '呼出': 'call out',
  '播放': 'play',
  '选择用户': 'select user',
  '默认值': 'Defaults',
  '级': 'class',
  '文字': 'Word',
  '公式编辑': 'formula editing',
  '保存并添加': 'save and add',
  '今天': 'today',
  '昨天': 'yesterday',
  '本周': 'this week',
  '本月': 'this month',
  '上个月': 'last month',
  '最近3个月': 'last 3 months',
  '最近七天': 'last seven days',
  '最近31天': 'last 31 days',
  '选择时间': 'selection period',
  '请选择时间': 'Please select a time',
  '首页': 'front page',
  '请先点击“显示报表”按钮获取相关信息': 'Please click the "Show Report" button first to obtain relevant information',
  '请在“队列搜索”中选择时间': 'Please select a time in Queue Search',
  '请在“队列搜索”中选择坐席': 'Please select a seat in "Queue Search"',
  '选择坐席': 'Choose a seat',
  '请选择坐席': 'Please select a seat',
  '显示报表': 'show report',
  '坐席': 'seat',
  '序号': 'serial number',
  '呼叫时间': 'call time',
  '总计': 'total',
  '流程编号': 'Process number',
  '客户电话': 'customer phone',
  '流程状态': 'Process status',
  '流程类型': 'Process type',
  '发起人': 'sponsor',
  '流程发起时间': 'Process start time',
  '摘要': 'Summary',
  '流程子状态': 'Process substate',
  '办理': 'handle',
  '办理人': 'transactor',
  '办理时间': 'Processing time',
  '办理备注': 'Handling remarks',
  '至': 'to',
  '格式': 'Format',
  '请输入文字': 'please enter text',
  '请选择图标': 'Please select an icon',
  '短信': 'Short message',
  '文本框': 'text box',
  '数据源': 'data source',
  '数据源不能为空': 'Data source cannot be empty',
  '静态': 'static',
  '动态': 'dynamic',
  '选项值重复': 'Duplicate option value',
  '是否允许半星': 'Whether to allow half stars',
  '默认': 'default',
  '详细地址': 'specific address',
  '过滤': 'filter',
  '点击下载': 'click to download',
  '请输入少于20个字符': 'Please enter less than 20 characters',
  '执行动作': 'perform action',
  '发送邮件': 'send email',
  '为': 'for',
  '不能为空': 'Can not be empty',
  '确认选择': 'Confirm selection',
  '新增': 'new',
  '新增&编辑': 'Add & Edit',
  '编辑图片': 'Edit pictures',
  '下载模板': 'Download template',
  '文件上传': 'File Upload',
  '刷新': 'refresh',
  '导入字段': 'Import fields',
  '导出模板名称': 'export template name',
  '请输入导出模板名称': 'Please enter export template name',
  '选中': 'checked',
  '加载更多数据': 'load more data',
  '没有更多数据': 'no more data',
  '您没有权限查看视图，请联系管理员': 'You do not have permission to check the view, please contact the administrator',
  '未配置uniqueid': 'uniqueid is not configured',
  '流程办理': 'Process',
  '请选择办理方式': 'Please select handling method',
  '办理备注不能为空': 'Remarks cannot be empty',
  '批量搜索': 'Bulk search',
  '请输入搜索内容': 'Please enter search content',
  '自动': 'automatic',
  '手动': 'manual',
  '邮件内容模板': 'Email Content Template',
  '无条件': 'unconditional',
  '按': 'according to',
  '天': 'sky',
  '小时': 'Hour',
  '分钟': 'minute',
  '状态设置': 'Status settings',
  '操作按钮': 'Action button',
  '子状态': 'substate',
  '手动输入': 'Manual entry',
  '已取消': 'Cancelled',
  '流程': 'process',
  '邮件': 'mail',
  '微信': 'WeChat',
  '抄送人': 'CC person',
  '号码': 'Number',
  '您确认导出所有数据吗?': 'Are you sure to export all data?',
  '设计': 'design',
  '粘贴': 'paste',
  '隐藏网格': 'hide grid',
  '复制成功': 'Copy successfully',
  '所属分类': 'category',
  '分值': 'Score',
  '请输入分值': 'Please enter a score',
  '备注不能为空': 'Remarks cannot be empty',
  '流转': 'circulation',
  '转办': 'Turn to do',
  '催办': 'urge',
  '表单': 'form',
  '未读消息': 'unread message',
  '标题': 'title',
  '内容': 'content',
  '公告': 'announcement',
  '登录': 'Log in',
  '就绪': 'ready',
  '离开': 'Leave',
  '一键ACE系统': 'One-click ACE system',
  '新建工单': 'Create new  work order',
  '个人信息': 'Personal information',
  '请输入至少六个字符': 'Please enter at least six characters',
  '密码长度为{0}-{1}位字符，且必须包含数字': 'Password is {0}-{1} characters long and must contain numbers',
  '密码不能包含空格，请重新输入': 'Password cannot contain spaces, please re-enter',
  '错误': 'mistake',
  '请输入正确的电话号码': 'Please enter the correct phone number',
  '字符': 'character',
  '秒': 'Second',
  '基础信息': 'basic information',
  '时间设置': 'time setting',
  '分': 'Minute',
  '时': 'Time',
  '从': 'from',
  '组织': 'organization',
  '所属': 'belong',
  '说明': 'illustrate',
  '分割线': 'Dividing line',
  '分组': 'grouping',
  '值': 'value',
  '选项': 'Options',
  '代码': 'code',
  '增加': 'Increase',
  '列': 'List',
  '行': 'Row',
  '水平': 'level',
  '垂直': 'vertical',
  '行内': 'Inline',
  '恢复': 'recover',
  '布局': 'layout',
  '警告': 'warn',
  '宽度': 'width',
  '高度': 'height',
  '校验': 'check',
  '属性': 'Attributes',
  '邮箱': 'Mail',
  '手机': 'mobile phone',
  '上传': 'upload',
  '职务': 'job title',
  '请输入姓名': 'Please enter your name',
  '请输入少于10个字符': 'Please enter less than 10 characters',
  '请输入正确的手机号码': 'Please enter the correct phone number',
  '请选择用户': 'Please select a user',
  '订单号': 'order number',
  '请输入订单号': 'Please enter order number',
  '时间': 'time',
  '待回复': 'pending reply',
  '已回复': 'Replied',
  '已解决': 'solved',
  '系统用户': 'system user',
  '就餐': 'dining',
  '会议': 'Meeting',
  '培训': 'training',
  '洗手间': 'Toilet',
  '其他': 'other',
  '发生事件': 'an event occurs',
  '且(and)': 'and (and)',
  '或(or)': 'or (or)',
  '那么, 执行动作': 'Then, perform the action',
  '请选择月份': 'Please select a month',
  '合计': 'total',
  '月份': 'month',
  '一': 'Mon',
  '二': 'Tue',
  '三': 'Wed',
  '四': 'Thu',
  '五': 'Fri',
  '六': 'Sat',
  '日': 'Sun',
  '模糊搜索': 'fuzzy search',
  '精确搜索': 'precise search',
  '工单编号': 'work order number',
  '工单子状态': 'Work order sub status',
  '当前办理人': 'current manager',
  '更新时间': 'update time',
  '订单编号': 'order number',
  '岁': 'age',
  '选择数据': 'select data',
  '请输入内容，且不能为纯空格字符': 'Please enter content, and cannot be pure space characters',
  '--没有更多数据--': '--No more data--',
  '--加载更多--': '--load more--',
  '周一': 'Monday',
  '周二': 'Tuesday',
  '周三': 'Wednesday',
  '周四': 'Thursday',
  '周五': 'Friday',
  '周六': 'Saturday',
  '周日': 'Sunday',
  '星期一': 'Monday',
  '星期二': 'Tuesday',
  '星期三': 'Wednesday',
  '星期四': 'Thursday',
  '星期五': 'Friday',
  '星期六': 'Saturday',
  '星期日': 'Sunday',
  '批量添加': 'Bulk add',
  '关键字': 'keywords',
  '基础': 'Base',
  '数据表': 'data sheet',
  '空': 'null'
}
